export const BRAND_GREEN = "#00B761";
export const BRAND_ORANGE = "#FF7A00";

export const ROLE_CONFIG = {
  producer: {
    color: BRAND_GREEN,
    bgTint: "#f0fdf4",
    ringColor: "#00B76122",
    label: "Producer / ರೈತ",
    labelShort: "Producer",
  },
  consumer: {
    color: BRAND_ORANGE,
    bgTint: "#fff7ed",
    ringColor: "#FF7A0022",
    label: "Consumer / ಗ್ರಾಹಕ",
    labelShort: "Consumer",
  },
};

export const LANGUAGE_CONFIG = {
  en: { label: "English" },
  kn: { label: "ಕನ್ನಡ" },
  hi: { label: "हिन्दी" },
};

export const COPY = {
  en: {
    chooseLanguageTitle: "Choose your language",
    chooseLanguageSubtitle: "Select one language to continue",
    continue: "CONTINUE",
    whoAreYou: "Who are you?",
    roleSubtitle: "Select your role to get started.",
    signUp: "Sign up",
    logIn: "Log in",
    fullName: "Full name",
    emailAddress: "Email address",
    password: "Password",
    createPassword: "Create a password",
    welcomeBack: "Welcome back",
    createAccount: "Create your account",
    signingIn: "Signing in…",
    signInArrow: "Sign in →",
    creatingAccount: "Creating account…",
    createAccountArrow: "Create account →",
    joiningAs: "Joining as a",
    forgotPassword: "Forgot password?",
    terms: "By signing up, you agree to our Terms of Service and Privacy Policy.",
    producerDesc: "I want to sell my fresh harvest directly to markets.",
    consumerDesc: "I want to discover producers and discuss produce directly with them.",
    selectRole: "Select a role to continue",
    continueAs: "Continue as",
    languageLabel: "Language",
  },
  kn: {
    chooseLanguageTitle: "ನಿಮ್ಮ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆ ಮಾಡಿ",
    chooseLanguageSubtitle: "ಮುಂದುವರೆಯಲು ಒಂದೇ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆ ಮಾಡಿ",
    continue: "ಮುಂದುವರೆಯಿರಿ",
    whoAreYou: "ನೀವು ಯಾರು?",
    roleSubtitle: "ಪ್ರಾರಂಭಿಸಲು ನಿಮ್ಮ ಪಾತ್ರವನ್ನು ಆಯ್ಕೆ ಮಾಡಿ.",
    signUp: "ಖಾತೆ ತೆರೆಯಿರಿ",
    logIn: "ಲಾಗ್ ಇನ್",
    fullName: "ಪೂರ್ಣ ಹೆಸರು",
    emailAddress: "ಇಮೇಲ್ ವಿಳಾಸ",
    password: "ಪಾಸ್ವರ್ಡ್",
    createPassword: "ಪಾಸ್ವರ್ಡ್ ರಚಿಸಿ",
    welcomeBack: "ಮತ್ತೆ ಸ್ವಾಗತ",
    createAccount: "ನಿಮ್ಮ ಖಾತೆ ರಚಿಸಿ",
    signingIn: "ಲಾಗ್ ಇನ್ ಆಗುತ್ತಿದೆ…",
    signInArrow: "ಲಾಗ್ ಇನ್ →",
    creatingAccount: "ಖಾತೆ ರಚಿಸಲಾಗುತ್ತಿದೆ…",
    createAccountArrow: "ಖಾತೆ ರಚಿಸಿ →",
    joiningAs: "ಇವರಾಗಿ ಸೇರಲಾಗುತ್ತಿದೆ",
    forgotPassword: "ಪಾಸ್ವರ್ಡ್ ಮರೆತಿರಾ?",
    terms: "ಖಾತೆ ತೆರೆಯುವುದರಿಂದ, ನೀವು ನಮ್ಮ ಸೇವಾ ನಿಯಮಗಳು ಮತ್ತು ಗೌಪ್ಯತಾ ನೀತಿಗೆ ಒಪ್ಪುತ್ತೀರಿ.",
    producerDesc: "ನನ್ನ ತಾಜಾ ಬೆಳೆಗಳನ್ನು ನೇರವಾಗಿ ಮಾರುಕಟ್ಟೆಗೆ ಮಾರಲು ಬಯಸುತ್ತೇನೆ.",
    consumerDesc: "ತೋಟದಿಂದ ನೇರವಾಗಿ ಉತ್ತಮ ಗುಣಮಟ್ಟದ ಉತ್ಪನ್ನಗಳನ್ನು ಖರೀದಿಸಲು ಬಯಸುತ್ತೇನೆ.",
    selectRole: "ಮುಂದುವರೆಯಲು ಪಾತ್ರವನ್ನು ಆಯ್ಕೆ ಮಾಡಿ",
    continueAs: "ಇವರಾಗಿ ಮುಂದುವರೆಯಿರಿ",
    languageLabel: "ಭಾಷೆ",
  },
  hi: {
    chooseLanguageTitle: "अपनी भाषा चुनें",
    chooseLanguageSubtitle: "जारी रखने के लिए एक भाषा चुनें",
    continue: "जारी रखें",
    whoAreYou: "आप कौन हैं?",
    roleSubtitle: "शुरू करने के लिए अपनी भूमिका चुनें.",
    signUp: "साइन अप",
    logIn: "लॉग इन",
    fullName: "पूरा नाम",
    emailAddress: "ईमेल पता",
    password: "पासवर्ड",
    createPassword: "पासवर्ड बनाएं",
    welcomeBack: "फिर से स्वागत है",
    createAccount: "अपना खाता बनाएं",
    signingIn: "साइन इन हो रहा है…",
    signInArrow: "साइन इन →",
    creatingAccount: "खाता बनाया जा रहा है…",
    createAccountArrow: "खाता बनाएं →",
    joiningAs: "के रूप में शामिल हो रहे हैं",
    forgotPassword: "पासवर्ड भूल गए?",
    terms: "साइन अप करके, आप हमारी सेवा शर्तों और गोपनीयता नीति से सहमत होते हैं.",
    producerDesc: "मैं अपनी ताज़ा फसल सीधे बाज़ार में बेचना चाहता हूँ.",
    consumerDesc: "मैं खेतों से सीधे उच्च गुणवत्ता वाला उत्पाद खरीदना चाहता हूँ.",
    selectRole: "जारी रखने के लिए भूमिका चुनें",
    continueAs: "के रूप में जारी रखें",
    languageLabel: "भाषा",
  },
};
